apiVersion: v1
kind: Service
metadata:
  name: api-tareas
  namespace: tareas-namespace
spec:
  type: NodePort
  selector:
    app: api-tareas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30301
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-tareas
  namespace: tareas-namespace
spec:
  type: NodePort
  selector:
    app: mysql-tareas
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30201
