apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balanceo-de-cargas-api-tareas
  namespace: tareas-namespace
spec:
  ingressClassName: traefik
  rules:
    - host: tareas.tareas-namespace.com
      http: 
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-tareas
                port:
                  number: 80