version: '3'
services:
  API_autenticacion:
    container_name: APIautenticacion
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-light:latest
    ports:
      - '8000:80'
    volumes:
      - ./apache_conf/laravel-site.conf:/etc/httpd/conf.d/laravel-site.conf


  API_tareas:
    container_name: APItareas
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-light:latest
    ports:
      - '8002:80'
    volumes:
      - ../.:/var/www/html
      - ./apache_conf/laravel-site.conf:/etc/httpd/conf.d/laravel-site.conf


  mysql_autenticacion:
    container_name: mysql_autenticacion
    image: mysql:8
    ports:
      - '8004:8004'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: usuariosDB
      MYSQL_TCP_PORT: 8004
  
  
  mysql_tareas:
    container_name: mysql_tareas
    image: mysql:8
    ports:
      - '8005:8005'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tareasBD
      MYSQL_TCP_PORT: 8005